# lb:
#   image: rancher/load-balancer-service
#   ports: [ 80, 8080 ]
#   links: [ web, api ]
#   labels:
#     io.rancher.loadbalancer.target.web: klouds.io:80=80
#     io.rancher.loadbalancer.target.api: klouds.io:8080=8080
web:
  image: ds0nt/klouds-ui
  ports: [ 2020 ]
  links: [ api ]
api:
  image: ds0nt/klouds-api
  expose: [ 48113 ]
  links: [ db ]
db:
  image: mongo
